### ISSUE TITLE
`-o pipefail` causes script to always fail

### ISSUE THREAD

**Issue by lfdebrux** [erbridge/github-branch-renamer#5]
Release v0.2.1 no longer works for me, I just see 

    ==> Collecting relevant repositories for 'lfdebrux'...

and then the script exits with status 1 and no message.

I believe the issue is the `pipefail` option, because removing it causes the script to run as expected.

Looking at the definition of `PARAMS` in https://github.com/erbridge/github-branch-renamer/blob/6724bc5fd0e185c0542fe1b6af5bdf8e63d481c5/gbr#L152-L161 I think this pipeline is expected to fail when there are no pages left to visit?

**Comment by erbridge** [comment]
Do you get an error code on exit?

**Comment by erbridge** [comment]
You're right. This should be fixed in `v2.2.3`.
